In [2]:
import numpy as np
import timeit

### Ex. 1

In [5]:
np.random.seed(123)
x = np.random.uniform(-4,4,30)

In [10]:
x[((x >= -2) & (x < -1)) | ((x >= 1) & (x <=2))]

array([ 1.57175348, -1.71088532,  1.75575176,  1.47863791, -1.25457587,
        1.83239766,  1.90396325,  1.07520767,  1.7956426 ,  1.77954706,
       -1.41632869, -1.10569076, -1.65028763,  1.04780899])

In [13]:
len(x[x >= 0])

15

In [12]:
np.mean(np.abs(x))

1.5260572308400788

In [14]:
np.amax(x)

3.846113587076924

In [15]:
np.amin(x)

-3.522576827123453

6

In [18]:
np.argmax(0 - np.abs(x))

8

In [19]:
x[8]

-0.15254478812511252

In [31]:
def nearest_n(array, number):
    amin = array[np.argmin(np.abs(x - number))]
    amax = array[np.argmax(np.abs(x - number))]
    return (amin, amax)

In [33]:
nearest_n(x, 2)

(1.9039632458562856, -3.522576827123453)

In [40]:
np.modf(x)[0]

array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
       -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
       -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
        0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ,
        0.07520767,  0.79545435,  0.7956426 ,  0.88818809,  0.77954706,
       -0.41632869, -0.10569076, -0.17389415, -0.65028763,  0.04780899])

In [41]:
x - np.trunc(x)

array([ 0.57175348, -0.71088532, -0.18518837,  0.41051815,  0.75575176,
       -0.61514832,  0.84611359,  0.47863791, -0.15254479, -0.86305985,
       -0.25457587,  0.83239766, -0.49142204, -0.52257683, -0.81564596,
        0.90396325, -0.54006616, -0.59638595,  0.25241099,  0.2546207 ,
        0.07520767,  0.79545435,  0.7956426 ,  0.88818809,  0.77954706,
       -0.41632869, -0.10569076, -0.17389415, -0.65028763,  0.04780899])

### Ex. 3

In [43]:
x

array([ 1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ,
        1.07520767,  2.79545435,  1.7956426 ,  0.88818809,  1.77954706,
       -1.41632869, -1.10569076, -2.17389415, -1.65028763,  1.04780899])

In [55]:
lead(x, 2)

array([-2.18518837,  0.41051815,  1.75575176, -0.61514832,  3.84611359,
        1.47863791, -0.15254479, -0.86305985, -1.25457587,  1.83239766,
       -0.49142204, -3.52257683, -0.81564596,  1.90396325, -2.54006616,
       -2.59638595,  0.25241099,  0.2546207 ,  1.07520767,  2.79545435,
        1.7956426 ,  0.88818809,  1.77954706, -1.41632869, -1.10569076,
       -2.17389415, -1.65028763,  1.04780899,         nan,         nan])

In [57]:
lag(x, 10)

array([        nan,         nan,         nan,         nan,         nan,
               nan,         nan,         nan,         nan,         nan,
        1.57175348, -1.71088532, -2.18518837,  0.41051815,  1.75575176,
       -0.61514832,  3.84611359,  1.47863791, -0.15254479, -0.86305985,
       -1.25457587,  1.83239766, -0.49142204, -3.52257683, -0.81564596,
        1.90396325, -2.54006616, -2.59638595,  0.25241099,  0.2546207 ])