In [60]:
import numpy as np

## Array basics

In [61]:
# one dimencional array
x = np.array([1,2,3,4])

In [62]:
# number of axes
x.ndim

1

In [63]:
# dimensions of the array
x.shape

(4,)

In [64]:
# two dimentional array
y = np.array([[1, 2, 3], [1, 2, 3]])

In [65]:
y.ndim

2

In [66]:
y.shape

(2, 3)

In [67]:
# total number of elements in array
y.size

6

In [68]:
# type of elements
y.dtype

dtype('int64')

In [69]:
y.dtype.name

'int64'

In [70]:
# bit size of each element
y.itemsize

8

In [71]:
# create array with dtype argument (numpy.int32, numpy.int16, and numpy.float64)
y = np.array([1,2,3], dtype='float64')

In [72]:
y

array([1., 2., 3.])

#### Change of shape

In [73]:
x2 = x.reshape(4, 1)
x2

array([[1],
       [2],
       [3],
       [4]])

In [74]:
# Order {‘C’, ‘F’, ‘A’}
x3 = x2.reshape(2, -1, order='F')
x3

array([[1, 3],
       [2, 4]])

In [75]:
x3.flatten()

array([1, 3, 2, 4])

In [76]:
x3.ravel()

array([1, 3, 2, 4])

#### Array creation (various methods)

In [77]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [78]:
np.array([[1,2], [2,4]])

array([[1, 2],
       [2, 4]])

In [79]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [81]:
np.empty((4,3))

array([[6.48224638e+170, 5.22411352e+257, 5.74020278e+180],
       [7.95445690e-322, 6.90248070e-310, 6.90248070e-310],
       [5.38016463e+097, 1.79862022e-052, 4.26262889e+126],
       [1.93501067e+184, 4.30256309e-096, 4.79243676e-322]])

In [82]:
np.arange(1, 10, 1).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
np.linspace(1, 9, 9, endpoint=False).reshape(3, -1)

array([[1.        , 1.88888889, 2.77777778],
       [3.66666667, 4.55555556, 5.44444444],
       [6.33333333, 7.22222222, 8.11111111]])

In [84]:
(np.arange(1, 11, 1) ** 2).reshape(-1, 5, order='F')

array([[  1,   9,  25,  49,  81],
       [  4,  16,  36,  64, 100]])

In [85]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [86]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [87]:
np.random.uniform(0, 10, 10)

array([5.98698786, 2.08224007, 4.15574497, 1.18764385, 1.16296992,
       3.57097413, 4.3556393 , 2.61912236, 2.1017819 , 1.2292385 ])

In [88]:
np.random.normal(0, 1, 10)

array([-0.19785593,  0.38998422, -0.42900609,  1.94901934,  1.36016043,
        0.32027117,  1.22208687, -0.59406827, -1.04749169, -0.86544535])

In [89]:
np.random.rand(2,3)

array([[0.83262641, 0.78283187, 0.33220729],
       [0.53877505, 0.48893789, 0.67855503]])

In [90]:
np.random.randint(20)

13

In [91]:
np.random.randint(1,20, (2,4))

array([[14, 19, 17,  4],
       [14,  1,  2, 14]])

In [92]:
np.random.randn(10)

array([-0.71003297,  0.76494514,  0.64079063, -0.27815734, -0.43616297,
       -0.82080486,  1.7087315 ,  1.29815601,  0.87446186,  0.18312668])

In [93]:
np.random.choice([1,3,4,5,6,7], 4, replace=False)

array([3, 5, 7, 1])

#### repeat and tile

In [94]:
np.repeat([1,2], 3)

array([1, 1, 1, 2, 2, 2])

In [95]:
np.repeat([1,2], (3,2))

array([1, 1, 1, 2, 2])

In [96]:
np.tile(4,5)

array([4, 4, 4, 4, 4])

In [97]:
np.tile([1,2,3], (4,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

#### vectors merging, columns/rows inserting

In [98]:
x

array([1, 2, 3, 4])

In [99]:
# vertical
np.vstack((x, [1,2,3,4]))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [100]:
# horizontal
np.hstack((x, [5,6]))

array([1, 2, 3, 4, 5, 6])

In [101]:
x = np.arange(9).reshape(3, -1)
np.insert(x, 2, [10, 11, 12], axis=1)

array([[ 0,  1, 10,  2],
       [ 3,  4, 11,  5],
       [ 6,  7, 12,  8]])

In [102]:
np.insert(x, 0, [0, 0, 0], axis=0)

array([[0, 0, 0],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [104]:
x = np.arange(2, 32, 2).reshape(3, -1)

In [105]:
np.append(x, np.array([1,2,3,4,5]).reshape(1, -1), axis=0)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [ 1,  2,  3,  4,  5]])

In [106]:
np.append(x, np.array([1,2,3]).reshape(-1, 1), axis=1)

array([[ 2,  4,  6,  8, 10,  1],
       [12, 14, 16, 18, 20,  2],
       [22, 24, 26, 28, 30,  3]])

#### r_ and c_

In [ ]:
np.r_[y, [1,2,3]]

In [ ]:
np.c_[1:6:3j, [7,8,9]]

### Basic Operations

In [ ]:
a = np.array([10,20, 30, 40])
b = np.array([1,2,3,4])

In [ ]:
a - b

In [ ]:
a + b

In [ ]:
a * b

In [ ]:
np.sin(a)

In [ ]:
np.cos(b)

In [ ]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

In [ ]:
A - B

In [ ]:
A * B

In [ ]:
A @ B

#### Universal functions

In [ ]:
x = np.array([True, False, True, False])
y = np.array([True, True, False, False])

In [ ]:
np.all([x, y], axis=0)

In [ ]:
np.any((x, y), axis=0)

In [ ]:
z = np.arange(9).reshape(3, -1)
np.argmax(z, axis=1)

In [ ]:
np.argmin(z, axis=1)

In [ ]:
np.sum(z, axis=0)

In [ ]:
# indices of max/min elements
ind_min = np.unravel_index()

#### Indexing

In [ ]:
x

In [ ]:
x[0,0]

In [ ]:
x[:,0]

In [ ]:
np.hstack((x, x[:,0:1]))

In [ ]:
x[x > 2]